name: hadolint
version: '1.2.4'
synopsis: Dockerfile Linter JavaScript API
description: A smarter Dockerfile linter that helps you build best practice Docker images.
category: Development
author: Lukas Martinelli
maintainer: me@lukasmartinelli.ch
copyright: Lukas Martinelli
license: GPL-3
homepage: https://github.com/hadolint/hadolint
git: git@github.com:hadolint/hadolint.git
extra-source-files: README.md
dependencies:
  - base >=4.8 && <5
  - parsec >=3.1
  - language-docker >=2.0.0
library:
  source-dirs: src
  exposed-modules:
    - Hadolint.Bash
    - Hadolint.Formatter
    - Hadolint.Rules
  dependencies:
    - &bytestring bytestring >=0.10
    - &split split >=0.2
    - &ShellCheck ShellCheck >=0.4.7
executables:
  hadolint:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hadolint
      - optparse-applicative <=0.14.0.0
      - gitrev >=1.3.1
    when:
    # OS X does not support static build https://developer.apple.com/library/content/qa/qa1118
    - condition: '!(os(osx))'
      ld-options:
        - -static
        - -pthread
tests:
  hadolint-unit-tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - *bytestring
      - *split
      - *ShellCheck
      - HUnit >=1.2
      - hspec
      - hadolint
